name: upm-subtree-split

on:
  push:
    branches:
      - main

jobs:
  upm-subtree-split:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: upm subtree split
      run: |
        # upm subtree split
        git config user.name github-actions
        git config user.email github-actions@github.com
        $packageDir = Get-Item -Path "**/Packages/com.*" | Select-Object -ExpandProperty FullName
        $packageDir = $packageDir.replace('${{ github.workspace }}/','')
        Write-Host $packageDir
        git subtree split --prefix="$packageDir" -b upm
        git checkout upm
        git fetch origin upm
        git rebase origin/upm --reapply-cherry-picks
        git push origin upm --force-with-lease --tags --set-upstream --verbose
      working-directory: ${{ github.workspace }}
      shell: pwsh
